.github/labels.yaml
Closes #11
GitHub ラベルの視認性を向上させ、コントリビューション関連のラベルを追加しました。
1. カテゴリーラベル
- `category/documentation`: `#0075CA` → `#A0AEC0` (グレー)
- `category/dependencies` との区別を明確にするため
2. 難易度ラベル
- `difficulty/hard`: `#1C3F75` → `#800080` (紫)
- `difficulty/medium`: `#2980B9` → `#FFA500` (オレンジ)
- `difficulty/easy`: `#3498DB` → `#90EE90` (薄緑)
- 難易度の違いをより直感的に表現するため、異なる色を使用
新しいセクション「Contribution Labels」を追加し、以下のラベルを定義：
1. `contributions welcome`
- 色: `#0075CA` (青)
- 説明: コントリビューションを歓迎する Issue を示す
2. `good first issue`
- 色: `#7058E0` (紫)
- 説明: 新規コントリビューターに適した Issue を示す
=> [All] GitHub ラベルの色とコントリビューション関連のラベルを追加

.editorconfig, .gitignore
SSIA
あると良いかなと最低限の設定ファイル追加しました
1. .editorconfig
2. .gitignore
=> .editorconfig, .gitignoreの追加

.github/CODEOWNERS
Closes #15
CODEOWNERS ファイルを作成し、各ディレクトリの管理者を設定しました。
以下のように設定しました：
* リポジトリ全体: @blendthink @a-skua @YumNumm
* /apps/app/: @FlutterKaigi/conference-app-2025
* /apps/dashboard/: @FlutterKaigi/infra-2025
* /apps/website/: @FlutterKaigi/conference-website-2025
なし
参考文献：
* https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
* https://github.com/FlutterKaigi/2024/blob/main/.github/CODEOWNERS
=> [All] CODEOWNERS の設定

.tool-versions, bun.lock, package.json
- Closes #18
mise によるバージョン管理を追加します。
- mise ( asdf 互換あり) で bun, flutter, nodejs のバージョン管理を開始
- bun.lock, package.json を新規作成し、supabase@2.20.12 を devDependencies に追加
- package.json に clean スクリプトを追加（`git clean -xdf node_modules`）
mise が導入してある前提で記載します。
```
mise install
bun install
```
- 参画手順の仕組み・ドキュメント化
- #20 にて実施します
なし
- https://mise.jdx.dev/
=> build: mise によるバージョン管理を追加

.github/workflows/check-spell.yaml, .vscode/extensions.json, bun.lock, cspell.jsonc, package.json
Closes #17
スペルチェックツール（CSpell）を導入し、プルリクエスト時に自動チェックを実行するように設定しました。
- CSpellの基本設定（`cspell.jsonc`）
- プロジェクト固有の用語（FlutterKaigi, Supabase, CODEOWNERS, bunx, marocchino）
- 無視するパス（node_modules, .dart_tool, 設定ファイルなど）
- 必要な辞書パッケージ（software-terms, dart, flutter, sql）
- GitHub Actionsワークフロー（`.github/workflows/check-spell.yaml`）
- プルリクエスト時に自動実行
- `.tool-versions` から bun のバージョンを読み込み
- スペルチェックの実行
- VS Code設定（`.vscode/extensions.json`）
- Code Spell Checker 拡張機能を推奨
- コード、コメント、ドキュメント内のタイプミスを自動検出
- 日本語・英語の両方に対応
- エディタに依存せず、全員が同じルールでチェック可能
- CI/CD パイプラインに組み込むことで、PRレビュー時の負担軽減
- チェックのタイミング：プルリクエスト作成時
- エラーが検出された場合、PRのチェックが失敗します
=> [All] CSpell の導入

apps/dashboard/lib/main.dart, cspell.jsonc
Closes #26
CSpell の警告を解消するために、以下の対応を行いました：
1. Xcode 関連ファイルを ignore リストに追加
2. Gradle 関連の単語を dictionary に追加
3. Flutter 関連の単語を dictionary に追加
4. `main.dart` の AppBar 表記を統一
以下のファイルを ignore リストに追加：
- `Runner.xcodeproj`
- `Runner.xcworkspace`
- `*.xcconfig`
- `*.xib`
- `*.storyboard`
- `*.plist`
以下の単語を dictionary に追加：
- `allprojects`
- `Subproject`
- `subprojects`
以下の単語を dictionary に追加：
- `cupertino`
- `main.dart` 内のコメントで `appbar` となっていた表記を `AppBar` に統一
今後も新しい単語や無視すべきファイルが出てきた場合は、適宜 `cspell.jsonc` を更新していく必要があります。
=> [All] CSpell 警告対応

.env.json, .github/workflows/terraform-apply.yaml, .github/workflows/terraform-plan.yaml, .gitignore, .sops.yaml, .tool-versions, mise.toml, terraform/.gitignore, terraform/README.md, terraform/supabase/README.md, terraform/supabase/backend.tf, terraform/supabase/production.tf, terraform/supabase/provider.tf, terraform/supabase/staging.tf, terraform/supabase/variables.tf
- Closes #2
- Terraformの準備
- miseにTerraform, TFLint, tfcmtを追加
- TFLint, tfcmtはCIで利用
- `.env.json`を作成し、[SOPS]で暗号化した状態でコミット 	
- CI/CDの構築
- PR作成時: TFLint, Terraform Plan
- mainへpush時: Terraform Apply
- supabaseのインスタンス作成
- `flutterkaigi-2025-production` `flutterkaigi-2025-staging`
- 中のスキーマは追って作成していきます
- [SOPS](https://github.com/getsops/sops)を利用して、`.env.json`を暗号化するようにしました
- `TF_VAR`から始まる値は、環境変数にセットされた後に TerraformのVariableとして使われます
- SOPSを利用して、暗号化されたものをコミットすることで.envをバージョン管理することができるようになりました
- 
- ローカルで、Terraform applyが正常に動作することは確認しました
- Terraform Destroyしておきました
- CD環境で正常に動作するかどうかは未検証です
=> [infra] Supabaseのインスタンスを作成するTerraformを追加

.github/workflows/terraform-apply.yaml, .github/workflows/terraform-plan.yaml
- Terraform lint, applyをGitHub Actionsから実行したい
- しかし、`terraform/**/*.tf`に変更が無い場合は実行できなかった
- 基本的には変更が無い場合は実行する必要がないが、エラー等で手動実行したいケースがある
- 環境変数をいじった時も考えうる
- 手動実行できるようにします
- 実行するtarget(`terraform/{target}`ディレクトリ)を入力できるようにしました
- 現状は、`supabase`しかないですが 今後`cloudflare`, `firebase`が増えると思います
=> [Infra] Terraformワークフローを手動実行できるように変更

.github/workflows/check-spell.yaml, .github/workflows/terraform-apply.yaml, .github/workflows/terraform-plan.yaml
Closes #35
check-spell ワークフローの bun セットアップを `.tool-versions` と `setup-bun` から `mise` に移行し、他のワークフローの mise-action の設定も最適化しました。
以下の変更を行いました：
1. `check-spell.yaml` のツール管理を `.tool-versions` から `mise` に移行
- `tool-versions-action` の使用を廃止
- `setup-bun` の代わりに `mise-action` を使用
- Bunのバージョン管理を mise に統一
2. 各ワークフローファイルの `mise-action` の設定を最適化
- 不要な `install: true` パラメータを削除
- インストール設定をシンプル化
これらの変更により：
- ツール管理の一貫性が向上
- ワークフローの設定がよりシンプルに
- メンテナンス性の向上
- この変更は GitHub Actions のワークフローの実行に影響を与えますが、機能的な変更はありません
- すべてのワークフローで mise を使用することで、ツールのバージョン管理がより統一的になります
=> [All] check-spell ワークフローの bun セットアップを mise に移行

pubspec.yaml
- Closes #56
Melos のスクリプトを追加します。
以下のスクリプトを追加しました：
- コード生成関連
- gen: build_runner と l10n の生成
- gen:build: build_runner によるコード生成
- gen:l10n: 多言語ファイル生成
- 差分ビルド機能 (HEAD/main)
- コード整形関連
- fix: dart fix の実行
- format: dart format の実行
- custom_lint の fix 実行
- テスト関連
- test: すべてのパッケージのテスト実行
- test:dart: Dart パッケージのテスト実行
- test:flutter: Flutter パッケージのテスト実行
なし
- Melos のスクリプト設定に関する参考: https://melos.invertase.dev/configuration/scripts
=> ci: melos のスクリプトを追加

mise.toml, tools/bootstrap.sh
- Closes #66
開発環境のセットアップを改善するため、bootstrap スクリプトを追加しました。
以下の変更を実施しました：
1. `mise.toml` にタスク定義を追加
- `bootstrap`: ワークスペースの初期化を実行
- `clean`: ワークスペースのクリーンアップを実行
2. `tools/bootstrap.sh` スクリプトを追加
- mise のインストール
- bun のパッケージインストール
- melos のブートストラップ
- リッチな出力フォーマットでステータスを表示
- エラーハンドリングの実装
- スクリプトは bash で実装し、エラーハンドリングを厳密に行っています
- 各ツールが見つからない場合はスキップし、インストール方法のガイダンスを表示します
- 実行時間の計測機能を追加し、セットアップにかかった時間を確認できます
`mise bootstrap` または `mise bs` を実行することで、以下のように出力されます。
```log
-> mise bs   
[bootstrap] $ ./tools/bootstrap.sh 
[INFO] Working directory: /Users/tatsutakein/workspace/flutterkaigi/2025
Step 1: mise install
mise all tools are installed
[✔] mise install
Step 2: bun install
bun install v1.2.10 (db2e7d7f)
+ @cspell/dict-dart@2.3.0
+ @cspell/dict-flutter@1.1.0
+ @cspell/dict-software-terms@5.0.5
+ …
```
=> ci: 参画時用のスクリプトを追加

.github/workflows/check-spell.yaml, cspell.jsonc, supabase/migrations/README.md
Closes #89
cspell の files オプション追加、enableGlobDot 設定、ignorePaths の整理、不要な dictionaryDefinitions/words の削除、スペルミス修正などを行いました。
- cspell.jsonc に files オプション・enableGlobDot を追加し、対象ファイルや隠しファイルも検出できるように変更
- ignorePaths を整理し、自動生成ファイルや隠しファイルを除外
- 不要になった dictionaryDefinitions, words を削除
- スペルチェックワークフローで bunx cspell lint を使用するよう修正
- supabase/migrations/README.md のスペルミス修正
- GitHub Actions 関連の用語を辞書に追加
|-|-|-|
| | | |
特になし
=> [All] fix: cspell 設定・スペルチェックワークフローの改善と不要定義の削除

.github/workflows/check-pr.yaml, .github/workflows/wc-check-changes.yaml, .github/workflows/wc-check-spell.yaml, cspell.jsonc
Closes #30
PR チェック用の GitHub Actions ワークフローを一本化し、管理・保守性を向上させました。
- これまで複数に分かれていた PR チェック関連のワークフローを `.github/workflows/check-pr.yaml` に統合しました。
- 変更がない場合のスキップ処理やスペルチェック、失敗時のステータスチェックなどを一元管理します。
- ワークフローの実行効率化と、今後の拡張・修正の容易さを目的としています。
N/A
- 詳細なワークフロー内容は `.github/workflows/check-pr.yaml` を参照してください。
- 参考: [peter-evans/create-or-update-comment](https://github.com/peter-evans/create-or-update-comment)
=> [All] ci: PR チェックするワークフローを一本化

analysis_options.yaml
#109
workspaces 設定により node_modules 内でエラーが発生していた件について、プロジェクト直下に analysis_options.yaml を新規作成し、node_modules ディレクトリを除外する設定を追加しました。
- `analysis_options.yaml` を新規作成
- 以下の内容で node_modules を除外
```yaml
analyzer:
exclude:
- "node_modules"
```
これにより、node_modules 配下の不要なエラーが表示されなくなります。
=> [All] fix: analysis_options.yaml で node_modules を除外

.github/workflows/deploy-bff.yaml
Closes #117
- タイトルの通りです
- Error: `/home/runner/work/_temp/8d5beace-a308-4cb5-b999-65ef2eec4114.sh: line 17: syntax error near unexpected token '('` 
- `if`文の中で変数`${{ steps.deploy-bff-production.outputs.LOG }}`をダブルクォートで囲ったことによる問題
- シングルクォートにすることでsyntax errorにならないはず
=> fix(cd): BFFのCDが落ちているので修正する

apps/website/lib/config.dart, apps/website/lib/src/routes/index.dart, apps/website/web/styles.css
Closes #{issue_number}
- デザインの微修正
- 開催日の表示
- モバイル表示だと場所名が見切れる問題を修正
- 開催日を「FlutterKaigi 2025」のあとに表示するように
- スポンサー募集開始日時を修正
- 場所名が具体的になったので接続詞を `at` に変更
=> [web] デザインの微修正&開催日をトップに表示するように

.env.json, .github/workflows/supabase-apply.yaml, dprint.jsonc, supabase/config.toml
- Google Sign Inを実現するために、Google OAuthのClient ID, Client SecretをSupabaseに登録しました
- Google Sign Inに関するGoogle Cloudの設定もTerraformで管理したかったのですが、Terraformから操作しようとしたところ、エラーが発生してしまい 調査に時間が掛かりそうなため断念しました (メモ参照)
- SupabaseにGoogle Sign Inに関わる設定をセットする部分について、Terraformで行おうとしたのですが 設定が反映されていなかったので、Supabase CLIの`supabase config push`を利用することにしました #120 
- SupabaseのProduction, Stagingは同様のGoogle Cloud Project (`flutterkaigi-2025`)を利用します
- Google Cloud Terraformのエラー
```log
╷
│ Error: Error creating Brand: googleapi: Error 400: Project must belong to an organization.
│ 
│   with google_iap_brand.flutterkaigi_brand,
│   on main.tf line 17, in resource "google_iap_brand" "flutterkaigi_brand":
│   17: resource "google_iap_brand" "flutterkaigi_brand" {
│ 
╵
```
=> [Infra] SupabaseにGoogle Sign inに関する設定をセット

docs/SPELL_CHECK.md
Closes #28
スペルチェック運用ルール（CSpellの導入・運用方法、カスタム辞書、CI連携、VS Code拡張など）をまとめた `docs/SPELL_CHECK.md` を新規追加しました。
- CSpellの設定例や公式ドキュメントへのリンクを記載
- カスタム辞書の運用方法、CI・ローカル・VS Codeでの利用方法を説明
- プロジェクト独自の単語追加手順や参考リンクも記載
（なし）
（なし）
=> [All] docs: スペルチェック運用ルール（CSpell）ドキュメント追加 #28

apps/dashboard/lib/main.dart
N/A
正常にアプリが機能するように修正しました。
- Riverpod 3.0.0-dev.12 から挙動が変わっており、監視しておかないと Provider の処理が中断してしまって `await container.read(authNotifierProvider.future);` の処理が戻ってこなくなってしまっていた
- https://github.com/rrousselGit/riverpod/blob/d22c032051ea279b381096cc1e129eb54814d404/packages/flutter_riverpod/CHANGELOG.md#full-change-list
- 事前に `listen` で監視して、必要な処理が完了したらクローズするようにした
https://github.com/user-attachments/assets/dad2aa9b-d3b7-4952-9696-961ec22dd02b
=> [Dashboard] fix: authNotifierProvider の監視とクローズ処理を追加し、ビルド時の中断を防止

apps/dashboard/lib/core/router/account.dart, apps/dashboard/lib/core/router/event.dart, apps/dashboard/lib/core/router/router.dart, apps/dashboard/lib/core/router/router.g.dart, apps/dashboard/lib/core/router/sponsor.dart, apps/dashboard/lib/features/account/ui/account_info_screen.dart, apps/dashboard/lib/features/account/ui/profile_edit_screen.dart, apps/dashboard/lib/features/account/ui/withdrawal_screen.dart, apps/dashboard/lib/features/event/ui/event_info_screen.dart, apps/dashboard/lib/features/news/ui/news_screen.dart, apps/dashboard/lib/features/sponsor/ui/sponsor_detail_screen.dart, apps/dashboard/lib/features/sponsor/ui/sponsor_edit_screen.dart, apps/dashboard/lib/features/sponsor/ui/sponsor_list_screen.dart
Closes #158
- event/sponsor/account 各タブごとに router 定義を分割
- SCREENS.md に基づくメイン画面以降の画面遷移ルートを実装
- GoRouter のルート定義を event.dart, sponsor.dart, account.dart に分割
- 各画面遷移サンプルを FilledButton で実装
- 編集・モーダル系画面（スポンサー編集、プロフィール編集、退会申請）は親 Navigator で表示されるよう parentNavigatorKey を設定
https://github.com/user-attachments/assets/1d6ee39e-c943-4b8b-a6d0-6c7bd389af63
=> [Dashboard] feat: メイン画面以降の画面遷移実装（event/sponsor/account分割・モーダル遷移対応）

.vscode/tasks.json
BFF用のDocker操作コマンド（up/down/clean/status）を`.vscode/tasks.json`に追加しました。
- `bff-up`: BFFエンジンのDocker Composeをバックグラウンドで起動（ビルド・不要コンテナ削除込み）
- `bff-down`: BFFエンジンのDocker Composeを停止
- `bff-clean`: BFFエンジンのDocker Composeを停止し、イメージ・ボリュームも削除
- `bff-status`: BFFエンジンのDocker Composeの状態確認
Issue: なし
=> chore: BFF用DockerコマンドをVSCodeタスクに追加

supabase/migrations/20250713065753_move_name_logo_from_company_drafts_to_companies.sql, supabase/migrations/20250713070601_add_description_website_url_to_company_drafts.sql, supabase/migrations/20250713070847_make_logo_name_not_null_in_companies.sql, supabase/schemas/001_companies.sql, supabase/schemas/003_company_drafts.sql
- companiesテーブルのlogo_nameカラムを必須（NOT NULL・空文字不可）に変更
- company_draftsテーブルにdescription, website_urlカラムを追加（どちらもNOT NULL・空文字不可）
- 企業の基本情報（name, logo_name）をcompany_draftsからcompaniesテーブルに移動
- 企業の基本情報（name, logo_name）は企業自身が変更できないものとし、companiesテーブルで一元管理する構造に変更しました。
- 企業の説明やWebサイトURLは変更申請（company_drafts）で管理するようにしました。
- これにより、企業の基本情報の整合性を担保しつつ、申請内容の柔軟な管理が可能となります。
=> chore: 企業テーブル構造の見直し（name/logo_nameの移動・必須化、company_drafts 拡張）

.idea/runConfigurations/flutter_run_dashboard_development_debug.xml
IntelliJ IDEAの実行設定ファイルに`--dart-define-from-file`引数を追加しました。
- `.idea/runConfigurations/flutter_run_dashboard_development_debug.xml`に開発用環境変数ファイルを指定する引数を追加
Closes #273
=> chore(dashboard): IDEAの実行設定にargs追加

supabase/seeds/005_news.sql
Closes #190
ニューステーブルにサンプルデータを追加しました。
`supabase/seeds/005_news.sql` に以下のニュースデータを追加しました：
- FlutterKaigi mini #4 @Kyoto 開催のお知らせ
- FlutterKaigi 2025 スポンサー募集開始のお知らせ
これらのデータは、アプリケーションでのニュース機能のテストに使用されます。
なし
=> [Infra]: ニュースデータの追加

.github/workflows/deploy-bff.yaml, bff/bridge/package.json, bff/bridge/wrangler.jsonc, bun.lock
BFFデプロイ時に発生していたCloudflare WorkersのビルドエラーとGitHub Actionsのログ出力エラーを修正しました。
1. **@cloudflare/containersパッケージの追加**
- `bun add @cloudflare/containers --cwd bff/bridge`で依存関係を追加
- Cloudflare Workersのビルドエラーを解決
2. **GitHub Actionsのログ出力修正**
- 不要な環境変数定義を削除
- 環境判定ロジックを`matrix.environment`を使用する形に改善
- 変数名の一貫性を確保（`log` → `LOG`）
3. **wrangler.jsoncの警告修正**
- `instances`を`max_instances`に変更（非推奨警告の解消）
4. **production環境での環境変数追加**
- `SUPABASE_PROJECT_ID`環境変数をproductionデプロイステップに追加
- `.github/workflows/deploy-bff.yaml`: GitHub Actionsのログ出力修正
- `bff/bridge/package.json`: @cloudflare/containersパッケージ追加
- `bff/bridge/wrangler.jsonc`: instances → max_instancesに変更
- `bun.lock`: 依存関係の更新
- workspace機能を活用して`bun`で依存関係を管理
- Cloudflare Workersのデプロイが正常に動作するよう修正
=> [BFF] fix: BFFデプロイのエラーを修正

bff/engine/pubspec.yaml, pubspec.lock, pubspec.yaml
差分が発生していたため、melos bs を実行して差分をコミットして、ついでに test パッケージのバージョンを更新し、pubspec.lock ファイルを更新しました。
- `bff/engine/pubspec.yaml`: test パッケージのバージョンを `^1.24.3` から `^1.25.15` に更新
- `pubspec.yaml`: melos の dev_dependencies に test パッケージを追加
- `pubspec.lock`: 依存関係のロックファイルを更新
- test パッケージを最新の安定版に更新
- 関連する依存関係（test_api, test_core など）も適切に更新
- pubspec.lock ファイルでバージョンが正しくロックされていることを確認
=> fix: test パッケージのバージョンを更新

bff/engine/lib/routes/ticket_api_service.dart, bff/engine/lib/routes/ticket_api_service.g.dart, packages/bff_client/lib/src/api/v1/news_api_client.g.dart, packages/bff_client/lib/src/api/v1/tickets_api_client.dart, packages/bff_client/lib/src/api/v1/tickets_api_client.g.dart, packages/bff_client/lib/src/api/v1/users_api_client.g.dart, packages/bff_client/lib/src/model/v1/tickets/user_tickets_response.dart, packages/bff_client/lib/src/model/v1/tickets/user_tickets_response.freezed.dart, packages/bff_client/lib/src/model/v1/tickets/user_tickets_response.g.dart, packages/bff_client/lib/src/src.dart, packages/db_client/lib/src/client/ticket/ticket_purchase_db_client.dart
- ユーザーの購入済みチケットとチェックアウト履歴を取得する新しいエンドポイント `/me` を追加しました。
- `UserTicketsResponse` モデルをエクスポートするように `src.dart` を更新しました。
- チケット購入情報を取得するメソッド `getUserAllTickets` を `TicketPurchaseDbClient` に追加しました。
Closes #{issue_number}
=> feat(ticket): 自分の購入済みチケット一覧を取得するAPIを追加

supabase/migrations/20250809065606_003_create_job_boards_table.sql, supabase/schemas/003_job_boards.sql
Issueはありません。
企業の求人情報を管理するためのjob_boardsテーブルを作成しました。
job_boardsテーブルを新規作成し、以下の要素を含みます：
- **テーブル構造**:
- `id`: companiesテーブルへの外部キー（smallint, PRIMARY KEY）
- `url`: 求人ページのURL（text, NOT NULL, UNIQUE）
- `alt_text`: 画像の代替テキスト（text, NOT NULL）
- `image_name`: 画像ファイル名（text, NOT NULL）
- **制約・バリデーション**:
- URLは`https?://`で始まる形式のみ許可
- alt_textとimage_nameは空文字列不可
- companiesテーブルとの外部キー制約（CASCADE DELETE）
- Row Level Security (RLS) を有効化
- **作成したファイル**:
- `supabase/schemas/003_job_boards.sql`: テーブルスキーマ定義
- `supabase/migrations/20250809065606_003_create_job_boards_table.sql`: マイグレーションファイル
Supabaseの宣言型データベーススキーマ機能を使用してテーブル定義を行い、`bunx supabase db diff`コマンドでマイグレーションファイルを生成しました。
N/A
READMEの命名規則に従い、`003_create_job_boards_table`という名前でマイグレーションファイルを作成しています。
=> [Infra] feat: job_boardsテーブルの作成

bff/engine/.env.example
ローカル開発環境用の設定を`.env.example`に追加・更新しました。
`bff/engine/.env.example`ファイルに以下の変更を行いました：
- `INTERNAL_API_URL=http://localhost:8787`を追加
- `X_API_KEY=xxx`を追加  
- `SUPABASE_URL`を`https://your-project.supabase.co`から`http://127.0.0.1:54321`に変更（ローカル開発用）
これらの変更により、開発者がローカル環境でアプリケーションを実行する際の設定がより明確になり、開発効率が向上します。
=> [Infra] fix: Update .env.example for local development

apps/dashboard/lib/core/gen/l10n/l10n.dart, apps/dashboard/lib/core/gen/l10n/l10n_ja.dart, apps/dashboard/lib/features/sponsor/data/sponsor.dart, apps/dashboard/lib/features/sponsor/data/sponsor_provider.dart, apps/dashboard/lib/features/sponsor/ui/sponsor_detail_screen.dart, apps/dashboard/lib/features/sponsor/ui/sponsor_edit_screen.dart, apps/dashboard/res/l10n/app_ja.arb, packages/db_client/lib/src/client/sponsor/sponsor_db_client.dart, packages/db_types/lib/src/models/sponsors.dart, packages/db_types/lib/src/models/sponsors.freezed.dart, packages/db_types/lib/src/models/sponsors.g.dart, supabase/migrations/20250816110128_rename_description_to_pr_text.sql, supabase/schemas/003_company_drafts.sql, supabase/seeds/003_company_drafts.sql
スポンサー詳細画面の「会社概要」を「PR 文章」に変更し、関連するフィールド名を`description`から`prText`に統一しました。
- **Sponsorモデル**: `description`フィールドを`prText`に変更
- **UIコード**: 表示テキストとフィールド参照を「PR 文章」に変更
- **l10n**: `sponsorDescription`を`sponsorPrText`に変更
- **スポンサープロバイダー**: フィールド参照を`prText`に変更
- **スキーマ**: `company_drafts.description`を`pr_text`に変更
- **マイグレーション**: `description`カラムを`pr_text`にリネームするマイグレーションを追加
- **シードファイル**: データ挿入時のカラム名を`pr_text`に変更
- **データベースクライアント**: SQLクエリの`description`を`pr_text`に変更
- **データベース型定義**: `CompanySponsorDetail.description`を`prText`に変更
- 14ファイル変更
- 84行追加、72行削除
1. **フィールド名の統一**: アプリケーション層からデータベース層まで一貫した命名規則を適用
2. **自動マイグレーション生成**: `supabase db diff`を使用してマイグレーションファイルを自動生成
3. **コード生成の更新**: `melos run gen:build`で生成されたコードを更新
https://github.com/user-attachments/assets/305c7262-2688-4f58-9d00-dae69659e509
- …
=> refactor: スポンサーのdescriptionフィールドをprTextに変更

supabase/config.toml
Supabase設定から不要になったcompany buckets設定を削除しました。
- `supabase/config.toml`から`[storage.buckets.companies]`セクションを削除
- 関連する設定（`public = true`、`objects_path = "seeds/storages/companies"`）も削除
この変更により、Supabaseのストレージ設定がより簡潔になり、不要な設定が除去されます。company bucketsの設定が実際に使用されていない場合、この設定の削除は適切です。
=> fix: company buckets設定の削除

apps/app/lib/features/account/ui/info/account_info_screen.dart
Issue 203で実装されたアカウント情報画面のUIから、「Sponsor」「Google」などのChips表示を削除しました。
- Issue 203でアカウント情報画面のUIが実装された
- 現在、一時的に不要な表示要素としてChips表示が含まれている
- シンプルなUIにするため、Chips表示を削除
- **Chips表示**: 「Sponsor」「Google」のラベルを表示するChipウィジェット
- **関連するスペーシング**: Chips表示の前後の適切なスペーシング
- `apps/app/lib/features/account/ui/info/account_info_screen.dart`
- `_UserInfoCard`クラス内のChips表示部分を削除
- スペーシングを適切に調整
```dart
Wrap(
crossAxisAlignment: WrapCrossAlignment.center,
spacing: 8,
runSpacing: 8,
// TODO: ユースケースから取得した情報を表示する
children: ['Sponsor', 'Google']
.map(
(text) => Chip(
label: Text(
text,
softWrap: true,
overflow: TextOverflow.ellipsis,
maxLines: 2,
),
),
)
.toList(),
),
```
- ✅ 静的解析エラーなし（`dart analyze`）
- ✅ Chips表示の完全削除
- ✅ スペーシングの適切な調整
- ✅ UIの一貫性維持
References #203
=> feat: アカウント情報画面からChips表示を削除

supabase/seeds/005_news.sql
お知らせの初期データ（seed data）を更新し、最新の情報を反映しました。
- **`FlutterKaigi mini #4 @Kyoto を開催`** → **`FlutterKaigi mini #4 @Kyoto を開催します`**
- **`FlutterKaigi 2025 スポンサー募集を開始`** → **`FlutterKaigi 2025 スポンサー募集について`**
- 終了期間を `2025-06-30` から `2025-08-01` に延長
1. **`FlutterKaigi mini #4 ふりかえり`**
- 開始: 2025-05-16 09:00:00+00
- 終了: なし（継続中）
- URL: https://medium.com/flutterkaigi/flutterkaigi-mini-4-ふりかえり-beca6b44f937
2. **`FlutterKaigi 2025 プロポーザル募集を開始`**
- 開始: 2025-06-23 09:00:00+00
- 終了: 2025-07-22 09:00:00+00
- URL: なし
3. **`FlutterKaigi 2025 当日ボランティアスタッフ募集`**
- 開始: 2025-08-07 09:00:00+00
- 終了: なし（継続中）
- URL: https://medium.com/flutterkaigi/flutterkaigi-2025-当日ボランティアスタッフ募集-02f97b5996a3
- `supabase/seeds/005_news.sql` ファイルを更新
- データの整合性と最新性を向上
- アプリ内のお知らせ表示により豊富な情報を提供
- ✅ 既存データの適切な更新
- ✅ 新規データの追加
- ✅ SQL構文の正確性
- …
=> feat: お知らせの初期データを更新

apps/app/lib/features/news/data/news_provider.dart, bff/database/drizzle/relations.ts, bff/database/drizzle/schema.ts, packages/bff_client/lib/src/model/v1/news/news_create_request.dart, packages/bff_client/lib/src/model/v1/news/news_create_request.freezed.dart, packages/bff_client/lib/src/model/v1/news/news_create_request.g.dart, packages/bff_client/lib/src/model/v1/news/news_update_request.dart, packages/bff_client/lib/src/model/v1/news/news_update_request.freezed.dart, packages/bff_client/lib/src/model/v1/news/news_update_request.g.dart, packages/db_client/lib/src/client/news/news_db_client.dart, packages/db_types/lib/src/tables/news.dart, packages/db_types/lib/src/tables/news.freezed.dart, packages/db_types/lib/src/tables/news.g.dart, supabase/migrations/20250831082239_make-news-starts-at-not-null.sql, supabase/schemas/005_news.sql
お知らせ（news）テーブルの `starts_at` カラムを NOT NULL に変更し、データベーススキーマとDartの型定義の整合性を向上させました。
- `supabase/schemas/005_news.sql` で `starts_at TIMESTAMP` を `starts_at TIMESTAMP NOT NULL` に変更
- お知らせの開始日時が必須項目となり、データの整合性が向上
- `bunx supabase db diff -f make-news-starts-at-not-null` でマイグレーションファイルを作成
- `supabase/migrations/20250831082239_make-news-starts-at-not-null.sql` が生成されました
- マイグレーションの動作確認を `bunx supabase db reset` で実施済み
- `packages/db_types/lib/src/tables/news.dart` で `startsAt` フィールドを `required` に変更
- `@RequiredDateTimeConverter()` アノテーションを使用して一貫性を保持
- `melos run gen:build` で生成ファイルを更新
- `apps/app/lib/features/news/data/news_provider.dart` で `createdAt` から `startsAt` を使用するように修正
- お知らせの開始日時として適切なフィールドを使用することで、ビジネスロジックの整合性が向上
- `starts_at` カラムが NOT NULL 制約を持つことで、お知らせの開始日時が確実に設定される
- データの整合性と品質が向上
- …
=> feat: newsテーブルのstarts_atカラムをNOT NULLに変更し、型安全性を向上

apps/app/lib/features/account/ui/profile_edit_screen.dart
プロフィール編集時に既存のアバターキーを保持するように修正しました。アバターを変更しない場合でも既存のアバターが保持されるようになります。
- `ProfileResponse`に`avatarKey`のextensionを追加
- プロフィール更新時に既存のアバターキーを取得してリクエストに含める
- アバターURLからパス部分を抽出してアバターキーとして使用
現在のプロフィール編集機能では、アバターを変更しない場合でも既存のアバターが失われてしまう問題がありました。この修正により、アバターを変更しない場合でも既存のアバターが適切に保持されるようになります。
- `ProfileResponse`にextensionを追加してアバターURLからアバターキーを抽出
- `ProfileUpdateRequest`に`avatarKey`パラメータを追加して既存のアバターキーを渡す
- アバターURLのパス部分（先頭の`/`を除く）をアバターキーとして使用
この修正により、ユーザーがプロフィールの他の情報（名前、コメント、SNSリンクなど）のみを変更する場合でも、既存のアバターが保持されるようになります。
=> feat: プロフィール編集時に既存のアバターキーを保持するように修正

apps/app/lib/core/router/router.dart
Google認証時のエラーメッセージ表示機能を修正し、ScaffoldMessengerエラーを解決しました。
- Google認証で`identity_already_exists`エラーが発生した際のSnackBar表示でScaffoldMessengerエラーが発生
- 1秒の固定遅延を使用していたが、適切なタイミングでSnackBarを表示できていなかった
1. **ログインコールバック処理の分離**
- ログインコールバックとエラーハンドリングの処理を独立した条件分岐に変更
- `queryParameters`変数を事前に取得してコードの可読性を向上
2. **エラーメッセージ表示の改善**
- 1秒の固定遅延を削除
- `WidgetsBinding.instance.addPostFrameCallback`を使用してフレーム描画完了後にSnackBarを表示
- Scaffoldが利用可能になったタイミングで確実にSnackBarを表示
- **適切なタイミング制御**: `addPostFrameCallback`でフレーム描画完了を待機
- **エラー解決**: ScaffoldMessengerのエラーを根本的に解決
- **パフォーマンス向上**: 不要な遅延を削除してレスポンス向上
- **コードの可読性**: 条件分岐を明確にして理解しやすく
https://github.com/user-attachments/assets/30c1e555-f2d4-4d24-8a0e-4a6726a1d14c
- [Flutter WidgetsBinding.addPostFrameCallback](https://api.flutter.dev/flutter/scheduler/WidgetsBinding/addPostFrameCallbac …
=> fix: Google認証エラーメッセージ表示のScaffoldMessengerエラーを解決

apps/app/lib/features/account/ui/info/account_info_screen.dart, apps/app/pubspec.yaml, pubspec.lock
アカウント情報画面でプロフィール画像を優先表示し、Google認証画像をフォールバック表示する機能を実装しました。
- アカウント情報画面のプロフィール画像表示ロジックを改良
- プロフィール画像が設定されている場合はそれを優先表示
- プロフィール画像がない場合はGoogle認証画像をフォールバック表示
- Google認証画像にはGoogleアイコンをオーバーレイで表示
- どちらの画像もない場合はデフォルトの人物アイコンを表示
- ローディング・エラー状態の適切な表示
- `_ProfileImage`ウィジェットとして独立したコンポーネントに分離
- `ConsumerWidget`として実装し、内部で`profileNotifierProvider`をwatch
- 段階的なフォールバック機能（プロフィール画像 → Google認証画像 → デフォルトアイコン）
- `font_awesome_flutter`依存関係を追加してGoogleアイコン表示を実現
- 責任の分離によりコードの可読性と保守性を向上
- 再利用可能なウィジェットとして設計
- 適切な状態管理（ローディング中やエラー時の表示）
https://github.com/user-attachments/assets/0075229c-3b5b-49d6-a12a-aac5af8a314e
- ユーザビリティの向上：どの画像が表示されているかが分かりやすいUI
- 既存のプロフィール編集機能との整合性を保持
- エラーハンドリングとローディング状態の適切な処理
=> feat: アカウント情報画面でプロフィール画像を優先表示

apps/app/lib/core/router/router.dart, apps/app/lib/core/ui/main/main_screen.dart
スポンサー機能を一時的に無効化し、後で簡単に再有効化できる状態を維持
- ルーターからSponsorBranchを動的に除外する方法を採用
- `$mainRoute`の`branches`から`/sponsors`パスを持つブランチを`whereNot`メソッドで動的に除外
- `MainScreen`のスポンサータブをコメントアウトしてUIレベルでも無効化
- `SponsorBranch`の定義や`$SponsorDetailRoute`などの生成されたコードは保持
- 後で再有効化する際は、コメントアウトされた部分を元に戻すだけで済む設計
https://github.com/user-attachments/assets/6dbfb1fe-de00-4e02-8e18-60f2582323d4
- `collection`パッケージの`whereNot`メソッドを使用してブランチを動的に除外
- コード生成に必要な定義は全て維持されているため、将来的な再有効化が容易
=> feat: スポンサー機能を一時的に無効化

apps/app/lib/features/account/ui/info/account_info_screen.dart
- ユーザー情報カードの周囲にパディングを追加
- アカウントの他の情報のテキストにパディングを追加し、レイアウトを整えた
=> fix: アカウント情報画面のUIを改善

apps/app/lib/core/gen/l10n/l10n.dart, apps/app/lib/core/gen/l10n/l10n_ja.dart, apps/app/res/l10n/app_ja.arb
イベント情報画面で表示されている曜日が間違っていた問題を修正しました。
- 2025年11月13日は木曜日だが、アプリでは「2025年11月13日(金)」と金曜日で表示されていた
- `apps/app/res/l10n/app_ja.arb`の`eventDate`を「2025年11月13日(金)」から「2025年11月13日(木)」に変更
- ローカライゼーションファイルを再生成して自動生成ファイルも更新
1. アプリを起動
2. イベント情報画面を表示
3. 日付が「2025年11月13日(木)」と正しく表示されることを確認
Fixes #406
=> fix: イベント情報画面の曜日を正しい木曜日に修正

.vscode/launch.json, bff/bridge/src/index.ts, bff/engine/lib/main.dart, bff/engine/pubspec.yaml, pubspec.lock, terraform/supabase/production.tf, terraform/supabase/staging.tf
FlutterアプリとBFFエンジンが同じポート8080を使用していたため、開発環境でポート競合が発生していました。この問題を解決するため、ポート番号を適切に分離しました。
- **Flutterアプリ**: ポート8080 → 3000（フロントエンド開発の標準）
- **BFFエンジン**: ポート8080のまま（APIサーバー）
- **CORS設定**: `localhost:3000`を許可するよう更新
- **Terraform設定**: Supabaseの`uri_allow_list`を`localhost:3000`に更新
- 開発環境でのポート競合が解消される
- ステージング・本番環境での認証フローが正常に動作する
- CORS設定が適切に更新される
ポート競合による開発環境の動作不良
=> fix: resolve port conflict between Flutter app and BFF engine

apps/app/lib/core/gen/i18n/i18n.g.dart, apps/app/lib/core/gen/i18n/i18n_en.g.dart, apps/app/lib/core/gen/i18n/i18n_ja.g.dart, apps/app/res/i18n/account/account_en.i18n.yaml, apps/app/slang.yaml
- Closes #280
アカウント設定画面の英語翻訳ファイルを追加し、言語フォールバック設定を実装しました。
- `account_en.i18n.yaml` - アカウント設定の英語翻訳を追加
- `slang.yaml` - 英語ファイルが存在しない場合の日本語へのフォールバック設定を追加
- slang による自動生成ファイルを更新
- プロフィール関連のテキスト
- ソーシャルリンク設定
- アバター画像のアップロード/削除メッセージ
- ゲストサインイン関連のテキスト
|           ゲスト           |           通常            |           編集            |
| :------------------------: | :------------------------: | :------------------------: |
| <img src="https://github.com/user-attachments/assets/d7d09832-8a11-4011-ad84-18bc90f6f7bb" width="300" /> | <img src="https://github.com/user-attachments/assets/431ca1c5-329a-416e-b6e2-a73658572305" width="300" /> |<img src="https://github.com/user-attachments/assets/8daaf926-c41b-412a-a051-4f18e500b0cc" width="300" /> |
|           利用規約           |           プライバシーポリシー …
=> chore(slang): アカウント関連の英語翻訳を追加

apps/app/environments/.env.dev, apps/app/environments/.env.prod, apps/app/environments/.env.stg, apps/app/lib/core/gen/i18n/i18n.g.dart, apps/app/lib/core/gen/i18n/i18n_en.g.dart, apps/app/lib/core/gen/i18n/i18n_ja.g.dart, apps/app/lib/core/provider/environment.dart, apps/app/lib/core/provider/environment.freezed.dart, apps/app/lib/core/provider/environment.g.dart, apps/app/lib/core/router/account.dart, apps/app/lib/core/router/router.dart, apps/app/lib/features/account/ui/info/account_info_screen.dart, apps/app/res/i18n/account/account_en.i18n.yaml, apps/app/res/i18n/account/account_ja.i18n.yaml, apps/app_catalog/lib/feature/account/account_info_screen.dart
Closes #420
アカウント情報画面に退会申請フォームへのリンクを追加し、ゲストユーザーの場合は非表示にする機能を実装しました。
1. **国際化ファイルの更新**
- `account_ja.i18n.yaml` に「退会申請」を追加
- `account_en.i18n.yaml` に「Withdrawal Request」を追加
2. **アカウント情報画面の更新**
- `AccountInfoScreen` に退会申請リンクを追加
- ゲストユーザー（`user.isAnonymous`）の場合は退会申請リンクを非表示にする条件分岐を実装
3. **ルーターの更新**
- `AccountInfoRoute` に退会申請フォームへの遷移機能を追加
- 環境変数 `WITHDRAWAL_FORM_URL` から退会申請フォームのURLを取得し、外部ブラウザで開く機能を実装
4. **環境設定の更新**
- 各環境（dev, stg, prod）の設定ファイルに退会申請フォームURLを追加
- ユーザーがアカウントを退会したい場合の申請手順を提供するため
- ゲストユーザーには退会申請が不要なため、通常ユーザーのみに表示するため
| Before | After |
| ------ | ----- |
| 退会申請リンクなし | <video src=https://github.com/user-attachments/assets/19ff5a36-4599-41d9-bcb1-bf3c6f1169f2 /> |
- 退会申請フォームは外部URLに遷移するため、環境変数でURLを管理
- ゲストユーザーの判定は `user.isAnonymous` を使用
- 国際化対応済み（日本語・英語）
=> feat: アカウント情報画面に退会申請フォームへのリンクを追加
