.github/workflows/terraform-apply.yaml, .github/workflows/terraform-plan.yaml, cspell.jsonc, terraform/supabase/README.md, terraform/supabase/backend.tfbackend.example
- Terraform applyを実行するWorkflowが失敗していた
- https://github.com/FlutterKaigi/2025/actions/runs/14614775827/job/41000571243
- `backend.tf`についてのドキュメントが不足していた
- https://github.com/FlutterKaigi/2025/pull/31#discussion_r2055022777
上記問題を修正しました
=> [Infra] Terraform Apply Workflowのバグ修正, ドキュメント更新

.github/workflows/terraform-apply.yaml, .github/workflows/terraform-plan.yaml, .gitignore, .tool-versions, mise.ci.toml, mise.toml
None
md, css, html, jsなどのフォーマッタとしてdeno使いたいので追加します
1. denoを.tool-versions追加
2. mise.tomlをmise.ci.tomlに変更
3. .gitignoreにwrangler追加
4. .github/workflow/*にMISE_ENV: ciを追加
None
None
=> 依存設定にdeno追加

.vscode/.gitignore, .vscode/extensions.json, .vscode/settings.json
- Closes #51
- `.vscode/settings.json`と`.vscode/extensions.json`を作成しました
- 詳しい説明は、コメント欄をご覧ください
=> [All] VSCodeの構成ファイルを追加

.github/workflows/deploy-website.yaml
- Closes #101
- Websiteデプロイワークフローのバグを修正しました
- Comment PR Jobは、PR作成, 変更によるWorkflow実行時のみ動くべきだが、if引数の設定が抜けていた
- `define-environment`の値がおかしくなっていたので修正
=> [Infra] Websiteデプロイワークフローのバグを修正

.github/workflows/deploy-website.yaml
- https://github.com/FlutterKaigi/2025/pull/102 で直っていなかった箇所を修正
=> [Infra] define-environment内での不要なカッコを削除(deploy-website)

apps/website/lib/config.dart
Closes #{issue_number}
Otemachi と PLACE の間が空いていませんでしたので、スペースを削除しました
=> fix: 会場名を修正（Otemachi と PLACE の間にスペースを追加）

apps/website/lib/src/routes/index.dart
- #133 の追加対応
SSIA
|    ![Screenshot 2025-05-12 at 21 04 23](https://github.com/user-attachments/assets/c6cb80a4-85d7-4b34-a28b-96c9c88d1c19)    |   ![Screenshot 2025-05-12 at 21 04 28](https://github.com/user-attachments/assets/0c6bc070-48d0-4caa-ad8a-f3d2e2cee577)    |        |
=> [web] トップページの日付の表記を英語表記に統一

.cspell/project-term.txt, packages/bff_client/lib/src/model/error/error_response.dart, packages/bff_client/lib/src/model/error/error_response.freezed.dart, packages/bff_client/lib/src/model/error/error_response.g.dart, packages/bff_client/pubspec.yaml, packages/bff_client/test/src/model/error/error_response_test.dart
> [!WARNING]
> 先に、
> - #122 
> - #124
>  
> をマージしてください
Closes #72
- BFFからのエラーレスポンスを表現するErrorResponse型を作成しました
=> [Infra] ErrorResponseの型を定義

apps/website/lib/config.dart
- Close #138
「反社会的勢力の排除に関して」へのリンク追加
|    ![Screenshot 2025-05-14 at 0 11 47](https://github.com/user-attachments/assets/4515ee45-943e-4888-abbd-fd4173bfc4d1)    |    ![Screenshot 2025-05-14 at 0 11 43](https://github.com/user-attachments/assets/198ff186-9ffc-4885-8012-79043a767bc0)   |        |
=> [Web] リンク「反社会的勢力の排除に関して」を追加

apps/website/lib/app.dart, apps/website/lib/src/pages/home.dart, apps/website/lib/src/pages/timeline.dart
Closes #165 
- タイムライン画面のUI作成をしました
- ..._createLanguageRoutesに追記
- home.dartにタイムライン画面を記載
- 現状のタイムライン画面の中身を作成
- フォントなどの調整
- 細かいデザインなどについては、最終的なUI調整はコンテンツ一通り揃ってから修正するという話になったので、ある程度実装ができていれば、Approvalをしていただけると幸いです。
https://416f937f-flutterkaigi-2025-website.flutter-kaigi.workers.dev/
=> [website] タイムライン画面のUI作成

apps/website/lib/src/components/staff_card.dart, apps/website/lib/src/pages/home.dart, apps/website/lib/src/pages/staff.dart, apps/website/web/styles.css
Closes #166 
- Staff画面のUI作成を作成しました
- Home画面にStaff画面を追加しました 
- アイコンの作成にあたって、CSSを使ってデザインの修正をしました
https://77be85d0-flutterkaigi-2025-website.flutter-kaigi.workers.dev/
=> [website] Staff画面のUI作成

apps/website/lib/app.dart, apps/website/lib/src/components/staff_card.dart
- ヘッダーのデザインを調整
- スタッフ一覧のデザインを調整
- ヘッダーのデザインを調整
- glassmorphismにしてみた
- スタッフ一覧のデザインを調整
- 全体的に小さく、横並びの量が多くなるように調整
=> [Web] ヘッダー・スタッフ一覧デザイン調整

apps/dashboard/lib/core/provider/environment.dart, apps/dashboard/lib/core/provider/environment.freezed.dart, apps/dashboard/lib/core/provider/environment.g.dart, apps/dashboard/lib/core/router/router.dart, apps/dashboard/lib/core/router/router.g.dart, apps/dashboard/lib/features/account/ui/info/account_info_screen.dart, apps/dashboard/lib/features/auth/data/notifier/auth_notifier.g.dart, apps/dashboard/lib/features/auth/data/provider/auth_service.g.dart, apps/dashboard/lib/features/news/data/news.freezed.dart, apps/dashboard/lib/features/news/data/news_provider.g.dart, apps/dashboard/lib/features/sponsor/data/sponsor_provider.g.dart, apps/dashboard/pubspec.yaml, apps/dashboard_catalog/pubspec.yaml, bff/engine/lib/provider/db_client_provider.g.dart, bff/engine/lib/provider/environments_provider.g.dart, bff/engine/lib/provider/supabase_client.g.dart, bff/engine/lib/provider/supabase_util.g.dart, bff/engine/pubspec.yaml, pubspec.lock
- Riverpod 3.0.0-dev.15 から Riverpod 3.0.0-dev.16二アップデートします
- アカウント画面で、ユーザのメールアドレスとアバター画像(仮)を表示します
- 今後、BFFのUser GET APIを通じて行うようにします
=> [Dashboard] メールアドレスとアバター画像を表示させる, Riverpodアップデート

apps/website/lib/src/pages/call_for_proposal.dart, apps/website/lib/src/pages/staff.dart
=> Dartコードのフォーマット

apps/website/lib/src/config/config.dart
hacomonoスポンサー情報の文言を更新しました。
`apps/website/lib/src/config/config.dart`のhacomonoスポンサー情報を最新の内容に更新しました。主な変更点：
- 会社説明の文言を簡潔に修正
- toC向け新サービス「FitFits」とFlutterの採用に関する情報を追加
- 文章の流れと読みやすさを改善
変更により、hacomonoの最新の事業内容とFlutterとの関わりがより明確に伝わるようになります。
=> [Website] chore: hacomonoスポンサー情報の文言を更新

.vscode/launch.json, terraform/supabase/production.tf, terraform/supabase/staging.tf
- SupabaseにリダイレクトURLを追加
- Flutter WebのHotReloadを有効化
- Flutter Webのデバッグ時は8080番で固定
=> chore: SupabaseにリダイレクトURLを設定 & Flutter Webデバッグ環境の整備

.github/workflows/deploy-conference-app-web.yaml, apps/app/bin/main.js, apps/app/wrangler.toml, bff/bridge/biome.json, bff/bridge/src/index.ts, bun.lock, terraform/supabase/staging.tf
This PR adds Cloudflare Workers deployment for the FlutterKaigi 2025 conference app.
- **Cloudflare Workers Integration**: Deploy Flutter web app to Cloudflare Workers
- **WebAssembly Support**: Use Flutter WebAssembly for better performance
- **Multi-Environment Support**: 
- Production: `2025-app.flutterkaigi.jp`
- Preview: `*-flutterkaigi-2025-conference-app.flutter-kaigi.workers.dev`
- **GitHub Actions Workflow**: Automated build and deployment
- **Static Asset Hosting**: Serve Flutter web assets efficiently
- **wrangler.toml**: Cloudflare Workers configuration
- **GitHub Actions**: `.github/workflows/deploy-conference-app-web.yaml`
- **Build Process**: Flutter WebAssembly build with `flutter build web --wasm`
- **Asset Binding**: Static assets served from `./build/web`
1. **Build**: …
=> ci: add conference app web deployment to Cloudflare Workers

bff/bridge/biome.json, bff/bridge/src/index.ts, packages/db_client/lib/src/client/db_client.dart, packages/db_client/lib/src/client/news/news_db_client.dart, packages/db_client/lib/src/client/profile/profile_db_client.dart, packages/db_client/lib/src/client/sponsor/sponsor_db_client.dart, packages/db_client/lib/src/client/ticket/ticket_checkout_db_client.dart, packages/db_client/lib/src/client/ticket/ticket_option_db_client.dart, packages/db_client/lib/src/client/ticket/ticket_purchase_db_client.dart, packages/db_client/lib/src/client/ticket/ticket_type_db_client.dart, packages/db_client/lib/src/client/user/user_db_client.dart
- Dart BFFのレスポンスが異様に遅い
- CPUの処理はそこまでかかっていないはずなので、Postgresの接続/通信に時間がかかっているものと思われる
- [HonoのServerTiming](https://hono.dev/docs/middleware/builtin/cache)でCloudflare Containersの処理にどのくらいかかっているかを可視化する
=> chore: Dart BFF <-> Postgres間のログを仕込む

bff/engine/compose.yaml, bff/engine/lib/routes/user_api_service.dart, packages/db_types/lib/src/models/user_and_user_roles.dart, packages/db_types/lib/src/models/user_and_user_roles.freezed.dart, packages/db_types/lib/src/models/user_and_user_roles.g.dart
- 匿名認証 -> Googleサインインした時に、AuthMetaDataの特定フィールドがNullになる
=> AuthMetaDataモデルのフィールドをnullableに変更し、関連するコードを更新

apps/website/lib/src/config/config.dart
=> Update proposal URL in config.dart

bff/payment-workflow-internal-api/src/workflows/TicketCheckoutWorkflow/TicketCheckoutWorkflow.ts
TicketCheckoutWorkflowにおいて、Stripeチェックアウトセッションの無効化処理でエラーが発生する問題を修正しました。
- Stripeセッションを無効化する前に、セッションの現在のステータスを取得するように変更
- セッションが "open" ステータスの場合のみ無効化処理を実行するよう条件分岐を追加
従来は無条件でセッションの無効化（expire）を実行していましたが、既に完了済みや期限切れのセッションに対して無効化処理を実行するとエラーが発生していました。
- `TicketCheckoutWorkflow.ts` の無効化処理ロジック
- 既存のワークフローの動作には影響なし（エラーが発生しなくなるだけ）
=> fix: Stripeセッションの状態チェック後に無効化処理を実行するよう修正

apps/website/lib/src/config/config.dart, apps/website/lib/src/pages/call_for_proposal.dart, apps/website/lib/src/pages/home.dart, apps/website/lib/src/pages/news.dart
Closes #448
ニュースヘッドラインとして最新5件表示するリンクを追加しました．
|   <img width="1003" height="6678" alt="2025 flutterkaigi jp_" src="https://github.com/user-attachments/assets/58a5fc19-d47f-4fd7-8470-c608b852ade1" />     |    <img width="1003" height="6814" alt="localhost_8080_" src="https://github.com/user-attachments/assets/5bb511d7-011e-46f3-89d5-f11db0197878" />   |        |
=> [website] ニュースヘッドライン追加

apps/website/lib/src/pages/home.dart
=> fix typo - staff section 

.cspell/web-term.txt, apps/website/lib/src/config/config.dart, apps/website/lib/src/pages/home.dart, apps/website/lib/src/pages/timeline.dart, apps/website/lib/text.dart, apps/website/web/styles.css
Closes #452
SSIA
仮置きですが，タイムラインをウェブ上に反映しました
|    <img width="1124" height="6197" alt="2025 flutterkaigi jp_" src="https://github.com/user-attachments/assets/2df4ad1b-cbbd-4849-b71b-39c13e798a28" />    |     <img width="1124" height="7513" alt="9036d955-flutterkaigi-2025-website flutter-kaigi workers dev_" src="https://github.com/user-attachments/assets/3a5308f7-b56b-4100-93ff-1a2251a52e9f" />  |        |
=> [website] タイムライン実装

terraform/sakuracloud/environments/production/main.tf
- `sakuracloud/environments/production/main.tf`
=> format: `sakuracloud/environments/production/main.tf`
